### ISSUE TITLE
CPU temperature 

### ISSUE THREAD

**Issue by Phaestion** [pd4d10/system-monitor#1]
Hi there!

I love using your extension. It helps me monitor my CPU while using Crostini under ChromeOS. What would be awesome is to also display CPU temperature somewhere. Is this possible with the Chrome APIs?

**Comment by pd4d10** [comment]
@TyeBHarrison @Phaestion Thanks for your suggestion. I’ve checked the latest API, and it does support temperature, but only at chrome os. Added to the plan of next release

**Comment by Phaestion** [comment]
@pd4d10 that would be awesome, thank you!

**Comment by Phaestion** [comment]
@TyeBHarrison yeah, I also use Cog to see the temperature but then I have to have another window open and it is quite a heavy app - as you also remarked.

**Comment by pd4d10** [comment]
Hi, the latest v1.5.0 has been published to Chrome Web Store, which adds CPU temperatures if available.

Feel free to reopen it if there is any problem.
