### ISSUE TITLE
Toolbar icon no longer shows usage graph

### ISSUE THREAD

**Issue by equalsJeffH** [pd4d10/system-monitor#13]
System Monitor Version 2.1.0
ChromeOS Version 128.0.6613.118 (Official Build) (64-bit)

System Monitor Toolbar icon no longer shows usage graph.  Instead, it is showing the system monitor logo.  "Pin to toolbar" is ON.

**Comment by pd4d10** [comment]
The fixed version has been submitted to Chrome Web Store and should be available soon.

Thanks for your feedback!
