### ISSUE TITLE
Something broke recentely

### ISSUE THREAD

**Issue by homayounshahri** [pd4d10/system-monitor#4]
On a pixel book (Chromebook), the CPUs 2 and 4 (1~4) show 100% usage constantly and the graph does not update on the widget icon. I verified that indeed the CPU usage was normal using the 'top' command on the Linux terminal. This behavior is recent and interestingly, everything works just fine on other Chromebooks and chromes running on PCs (Linux). I am running Chrome version 77. The previous issue (#3) that was reported is precisely what I am observing (same exact behavior). 

Thanks.

**Comment by pd4d10** [comment]
Thanks for your report! Let's discuss it in #3
