### ISSUE TITLE
Open as new window broken

### ISSUE THREAD

**Issue by Alex313031** [pd4d10/system-monitor#5]
It used to work, but now when you try to open it as a new window it says your file was not found (ERR_FILE_NOT_FOUND). I have tested on multiple versions of chromium os, chrome os, and cloudready, as well as chromium/chrome on windows. I thought it just broke from an os update, but as you can see it is a platform independent bug that is on your side. The latest update to the .crx must have something to do with it. I am reporting this because it is annoying to have it not work, because I like to keep it open as a sort of task manager for chromium os based distros.

**Comment by pd4d10** [comment]
Hi, @Alex313031 , thanks for your report!

v1.5.1 gets this issue fixed and has been published. Chrome web store has a review process now, so it  might take several days to get auto updates
